# Generated by Django 3.0.5 on 2020-04-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relat',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
